stages:
  - docker-build
  - deploy

docker-build:
  stage: docker-build
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key.pem
    - chmod 400 key.pem
  script:
    - ssh -o StrictHostKeyChecking=no -i key.pem $USER_NAME@$PROD_SERVER_IP "export GPG_TTY=$(tty) && sudo rm -rf 1712585_1612094_1612149_fe"
    - ssh -o StrictHostKeyChecking=no -i key.pem $USER_NAME@$PROD_SERVER_IP "export GPG_TTY=$(tty) && git clone https://$USER_GIT_LAB:$PW_GIT_LAB@gitlab.com/hoangman1108/1712585_1612094_1612149_fe.git"
    - ssh -o StrictHostKeyChecking=no -i key.pem $USER_NAME@$PROD_SERVER_IP "export GPG_TTY=$(tty) && cd 1712585_1612094_1612149_fe && docker build . -t 1712585_1612094_1612149_fe"
deploy:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key.pem
    - chmod 400 key.pem

  script:
    - ssh -o StrictHostKeyChecking=no -i key.pem $USER_NAME@$PROD_SERVER_IP "docker stop 1712585_1612094_1612149_fe || true && docker rm 1712585_1612094_1612149_fe || true"
    - ssh -o StrictHostKeyChecking=no -i key.pem $USER_NAME@$PROD_SERVER_IP "docker run -p 3000:3000 -d --name 1712585_1612094_1612149_fe 1712585_1612094_1612149_fe"
