export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const GET_ME_SUCCESS = "GET_ME_SUCCESS";
export const GET_ME_FAIL = "GET_ME_FAIL";
export const GET_ME_INFO = "GET_ME_INFO";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LIST_CLASS_SUCCESS = "LIST_CLASS_SUCCESS";
export const LIST_CLASS_FAIL = "LIST_CLASS_FAIL";

export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAIL = "CREATE_CLASS_FAIL";

export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAIL = "DELETE_CLASS_FAIL";

export const INVITE_SUCCESS = "INVITE_SUCCESS";
export const INVITE_FAIL = "INVITE_FAIL";

export const SET_INFO_REGISTER = "SET_INFO_REGISTER";
export const RESET_INFO_REGISTER = "RESET_INFO_REGISTER";
